name: Build, Push Docker image and Update Deployment

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/prometheus-astronauts-exporter

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # permite fazer git push depois

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set IMAGE_TAG (git-SHA curto)
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "IMAGE_TAG=git-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (latest + git-SHA)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.IMAGE_TAG }}

      - name: Update image tag in k8s/deployment.yaml
        run: |
          sed -i "s#${{ env.IMAGE_NAME }}:latest#${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.IMAGE_TAG }}#g" k8s/deployment.yaml
          echo "Updated k8s/deployment.yaml to use tag ${{ steps.vars.outputs.IMAGE_TAG }}"

      - name: Commit updated deployment.yaml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ steps.vars.outputs.IMAGE_TAG }}" || echo "No changes to commit"
          git push